[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
aioquic = "^1.2.0"
dnslib = "^0.9.24"
click = "^8.1.7"
pylsqpack = { path = "pylsqpack", develop = true }


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
